### ISSUE TITLE
Upgrade to premium button does not work

### ISSUE THREAD

**Issue by mstibbard** [jarrodwatts/next-firebase-stripe#1]
**Issue:**

The button sending the user to the Stripe checkout does not work.

Setup:

- Clone of this directory
- NPM v7.13.0
- Nodejs v16.1.0

**Steps to reproduce:**
1. Clone the repo & open directory in VSCode
2. Run `npm install`
3. Create .env.local with API keys
```
NEXT_PUBLIC_FIREBASE_API_KEY=<your-api-key>
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=<your-auth-domain>
NEXT_PUBLIC_FIREBASE_PROJECT_ID=<your-project-id>
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=<your-storage-bucket>
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=<your-sender-id>
NEXT_PUBLIC_FIREBASE_APP_ID=<your-firebase-app-id>
```
3. Add stripe publishable key to `/stripe/initializeStripe.ts`. E.g. `pk_test_XXX`
4. Update `/stripe/createCheckoutSession.ts` with the product price ID from stripe. E.g. `price_XXX`
5. Run `npm run dev`

**Result:**

- Log in works ✅
- Display name shows when logged in ✅
- "Upgrade to premium!" button does nothing ❌

**Solution:**
Set up a business name in Stripe. If you check the Stripe Dashboard logs (Developers > Logs) it will show a bunch of failures with a helpful error message. 

No doubt someone else will have the issue so I'll leave this here.

Maybe add this to your write-up :)

**Comment by jarrodwatts** [comment]
Thanks for bringing that up mate!

So you just fixed it by adding a name to your Stripe business? If so, I will be sure to edit the steps to include that.

**Comment by mstibbard** [comment]
Correct.

My Stripe Logs showed a bunch of `400 ERR POST /v1/checkout/sessions` which when opened had a help error saying:
`invalid_request_error In order to use Checkout, you must set an account or business name at https://dashboard.stripe.com/account.`

**Comment by jarrodwatts** [comment]
Added it to the blog post, thanks again for raising this @mstibbard !
